//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheques()
        {
            this.Cobros = new HashSet<Cobros>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int idCheque { get; set; }
        public bool activo { get; set; }
        public string banco { get; set; }
        public System.DateTime fechaEmitido { get; set; }
        public System.DateTime fechaCobro { get; set; }
        public bool cobrado { get; set; }
        public int idTercero { get; set; }
        public decimal monto { get; set; }
        public string numCheque { get; set; }
        public string idUsuario { get; set; }
        public bool enBlanco { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Terceros Terceros { get; set; }
        public virtual AspNetUsers Editado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobros> Cobros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
