//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CondomiBaseEntities : DbContext
    {
        public CondomiBaseEntities()
            : base("name=CondomiBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cheques> Cheques { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<DetalleIngresos> DetalleIngresos { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<LogCobranzas> LogCobranzas { get; set; }
        public virtual DbSet<LogEquipos> LogEquipos { get; set; }
        public virtual DbSet<MovimientosEquipos> MovimientosEquipos { get; set; }
        public virtual DbSet<Presupuestos> Presupuestos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terceros> Terceros { get; set; }
        public virtual DbSet<TipoCuentas> TipoCuentas { get; set; }
        public virtual DbSet<TipoTerceros> TipoTerceros { get; set; }
        public virtual DbSet<Transferencias> Transferencias { get; set; }
        public virtual DbSet<ModelosEquipos> ModelosEquipos { get; set; }
        public virtual DbSet<TipoServicios> TipoServicios { get; set; }
        public virtual DbSet<DetallePresupuesto> DetallePresupuesto { get; set; }
        public virtual DbSet<DetalleEgresos> DetalleEgresos { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<HorasNoTrabajadas> HorasNoTrabajadas { get; set; }
        public virtual DbSet<Sueldos> Sueldos { get; set; }
        public virtual DbSet<HorasTrabajadasTecnico> HorasTrabajadasTecnico { get; set; }
        public virtual DbSet<ProximasCompras> ProximasCompras { get; set; }
        public virtual DbSet<DetalleMantenimientoPreventivo> DetalleMantenimientoPreventivo { get; set; }
        public virtual DbSet<MantenimientoPreventivo> MantenimientoPreventivo { get; set; }
        public virtual DbSet<Vales> Vales { get; set; }
        public virtual DbSet<Cobros> Cobros { get; set; }
        public virtual DbSet<Adelantos> Adelantos { get; set; }
        public virtual DbSet<PlanCuentas> PlanCuentas { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<TipoEgresos> TipoEgresos { get; set; }
        public virtual DbSet<TipoIngresos> TipoIngresos { get; set; }
        public virtual DbSet<Egresos> Egresos { get; set; }
    }
}
