//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleIngresos
    {
        public int idDetalleIngreso { get; set; }
        public int idIngreso { get; set; }
        public decimal monto { get; set; }
        public int idTipoIngreso { get; set; }
        public int cantidad { get; set; }
    
        public virtual Ingresos Ingresos { get; set; }
        public virtual TipoIngresos TipoIngresos { get; set; }
    }
}
