//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePresupuesto
    {
        public int idDetallePresupuesto { get; set; }
        public int idPresupuesto { get; set; }
        public int idModeloEquipo { get; set; }
        public int cantidad { get; set; }
        public decimal precioDia { get; set; }
        public decimal precioHora { get; set; }
        public decimal costoHora { get; set; }
        public decimal costoDia { get; set; }
        public int idTercero { get; set; }
        public int horas { get; set; }
        public int dias { get; set; }
        public string observaciones { get; set; }
    
        public virtual ModelosEquipos ModelosEquipos { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
        public virtual Terceros Terceros { get; set; }
    }
}
