//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMantenimientoPreventivo
    {
        public int idDetalleMantenimientoPreventivo { get; set; }
        public int idMantenimientoPreventivo { get; set; }
        public int idEquipo { get; set; }
        public string chequeadoPor { get; set; }
        public Nullable<System.DateTime> fechaChequeado { get; set; }
        public estadoMantenimientoPreventivo estado { get; set; }
        public string observaciones { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual MantenimientoPreventivo MantenimientoPreventivo { get; set; }
    }
}
