//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egresos()
        {
            this.DetalleEgresos = new HashSet<DetalleEgresos>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int idEgreso { get; set; }
        public bool activo { get; set; }
        public string descripcion { get; set; }
        public string factura { get; set; }
        public tiposFacturas tipoFactura { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public System.DateTime fechaGenerada { get; set; }
        public string idUsuario { get; set; }
        public int idTercero { get; set; }
        public bool enBlanco { get; set; }
        public int idEvento { get; set; }
        public decimal impuestosInternos { get; set; }
        public decimal ingresosBrutos { get; set; }
        public decimal iva { get; set; }
        public decimal percepcionIva { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
        public Nullable<int> idPlanCuentas { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers Editado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEgresos> DetalleEgresos { get; set; }
        public virtual Eventos Eventos { get; set; }
        public virtual PlanCuentas PlanCuentas { get; set; }
        public virtual Terceros Terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
