//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoPreventivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoPreventivo()
        {
            this.DetalleMantenimientoPreventivo = new HashSet<DetalleMantenimientoPreventivo>();
        }
    
        public int idMantenimientoPreventivo { get; set; }
        public string descripcion { get; set; }
        public string idUsuario { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
        public System.DateTime fechaGenerado { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public prioridades prioridad { get; set; }
        public bool activo { get; set; }
        public int idModelo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers Editado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimientoPreventivo> DetalleMantenimientoPreventivo { get; set; }
        public virtual ModelosEquipos ModelosEquipos { get; set; }
    }
}
