//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelosEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelosEquipos()
        {
            this.Equipos = new HashSet<Equipos>();
            this.DetallePresupuesto = new HashSet<DetallePresupuesto>();
            this.MantenimientoPreventivo = new HashSet<MantenimientoPreventivo>();
        }
    
        public int idModelo { get; set; }
        public bool activo { get; set; }
        public string descripcion { get; set; }
        public decimal costoHora { get; set; }
        public decimal costoDia { get; set; }
        public int idTipoServicio { get; set; }
        public decimal precioHora { get; set; }
        public decimal precioDia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual TipoServicios TipoServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePresupuesto> DetallePresupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoPreventivo> MantenimientoPreventivo { get; set; }
    }
}
