//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosEquipos
    {
        public int idMovimientoEquipo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string idUsuario { get; set; }
        public Nullable<int> idEvento { get; set; }
        public int idEquipo { get; set; }
        public tipoMovimiento tipoMovimiento { get; set; }
        public string codigoBarras { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Eventos Eventos { get; set; }
        public virtual AspNetUsers Editado { get; set; }
    }
}
