//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int idPago { get; set; }
        public int idEgreso { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public int idCuenta { get; set; }
        public string idUsuario { get; set; }
        public decimal retenido { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
        public Nullable<int> idCheque { get; set; }
        public Nullable<int> idAdelanto { get; set; }
    
        public virtual Adelantos Adelantos { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers Editado { get; set; }
        public virtual Cheques Cheques { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Egresos Egresos { get; set; }
    }
}
