//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuestos()
        {
            this.DetallePresupuesto = new HashSet<DetallePresupuesto>();
        }
    
        public int idPresupuesto { get; set; }
        public bool activo { get; set; }
        public int idEvento { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string idUsuario { get; set; }
        public estadoPresupesto estado { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
        public Nullable<probabilidadPresupuesto> probabilidad { get; set; }
        public Nullable<decimal> bonificacion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePresupuesto> DetallePresupuesto { get; set; }
        public virtual Eventos Eventos { get; set; }
        public virtual AspNetUsers Editado { get; set; }
    }
}
