//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transferencias()
        {
            this.Vales = new HashSet<Vales>();
        }
    
        public int idTransferencia { get; set; }
        public int idCuentaOrigen { get; set; }
        public int idCuentaDestino { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public string descripcion { get; set; }
        public string idUsuario { get; set; }
        public string editadoPor { get; set; }
        public Nullable<System.DateTime> fechaEditado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Cuentas Cuentas1 { get; set; }
        public virtual AspNetUsers Editado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vales> Vales { get; set; }
    }
}
